// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Children");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2015, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            Name = "Tanvir Ahmed"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2018, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            Name = "Ayesha Ahmed"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2016, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 2,
                            Name = "Siam Rahman"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2019, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 7,
                            Name = "Nusrat Islam"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(2020, 9, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 7,
                            Name = "Fahim Islam"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NID")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NID")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasicSalary = 50000m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            NID = "1234567890",
                            Name = "Md. Hasan Ahmed",
                            Phone = "+8801712345678",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            BasicSalary = 45000m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Human Resources",
                            NID = "9876543210",
                            Name = "Moushumi Begum",
                            Phone = "+8801812345678",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            BasicSalary = 52000m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Finance",
                            NID = "11223344556671234",
                            Name = "Tanvir Rahman",
                            Phone = "+8801612345678",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            BasicSalary = 48000m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            NID = "22334455667781234",
                            Name = "Fatima Khatun",
                            Phone = "+8801912345678",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            BasicSalary = 47000m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Operations",
                            NID = "3344556677",
                            Name = "Abdul Karim",
                            Phone = "+8801512345678",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            BasicSalary = 46000m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "IT Support",
                            NID = "4455667788",
                            Name = "Nasrin Akter",
                            Phone = "+8801412345678",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            BasicSalary = 55000m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            NID = "55667788991121234",
                            Name = "Rafiqul Islam",
                            Phone = "+8801312345678",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            BasicSalary = 44000m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Human Resources",
                            NID = "66778899002231234",
                            Name = "Sultana Razia",
                            Phone = "+8801212345678",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            BasicSalary = 53000m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Finance",
                            NID = "7788990011",
                            Name = "Jalal Uddin",
                            Phone = "+8801112345678",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            BasicSalary = 49000m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            NID = "8899001122",
                            Name = "Ayesha Siddika",
                            Phone = "+8801012345678",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Spouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("NID")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("NID")
                        .IsUnique();

                    b.ToTable("Spouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            NID = "1111222233",
                            Name = "Rima Ahmed"
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 2,
                            NID = "2222333344",
                            Name = "Shakib Rahman"
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 7,
                            NID = "33334444555561234",
                            Name = "Shapla Khatun"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Child", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany("Children")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.Spouse", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithOne("Spouse")
                        .HasForeignKey("Domain.Entities.Spouse", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Spouse");
                });
#pragma warning restore 612, 618
        }
    }
}
